// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdkspgeqajulgicqxwmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRka3NwZ2VxYWp1bGdpY3F4d21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDQ3NzMsImV4cCI6MjA3Mzk4MDc3M30.X315A7UYI0HFIkcUMhOFoXUPKlnCTBej8DH769f7kqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});